unstable_features = true
imports_granularity = "Item"
imports_layout = "HorizontalVertical"
reorder_impl_items = true
where_single_line = true
fn_params_layout = "Vertical"
group_imports = "StdExternalCrate"
