primary_assistant = ["main"]

[assistants.cerebras]
api = "cerebras"
model = "zai-glm-4.7"
[assistants.gpt]
api = "openai"
model = "gpt-5.1-codex-mini"
effort = "low"
[assistants.llama]
api = "llama"
model = "dummy"
[assistants.zai]
api = "zai"
model = "glm-5"

[apis.openrouter]
base_url = "https://openrouter.ai/api/v1"
key_command = "cat /run/agenix/openrouter"
[apis.llama]
base_url = "http://anuramat-bgm5:11343/v1"
developer_as_user = true
[apis.openai]
base_url = "https://api.openai.com/v1"
key_command = "cat /run/agenix/openai"
[apis.cerebras]
# TODO -- add passthrough params; cerebras-specific -- clear_thinking: false
base_url = "https://api.cerebras.ai/v1"
key_command = "cat /run/agenix/cerebras"
kind = "chat_completions"
reasoning_key = "reasoning"
reasoning_as_output = "think"
[apis.zai]
base_url = "https://api.z.ai/api/coding/paas/v4"
key_command = "cat /run/agenix/zai"
kind = "chat_completions"
reasoning_key = "reasoning_content"

[bash]
  cmd = [
    "bash",
    "-lc",
  ]
  [bash.bwrap]
    bin = "bwrap"
    args = [
      "--die-with-parent",
      "--proc",
      "/proc",
      "--dev",
      "/dev",
    ]
    [[bash.bwrap.stages]]
      ro = [
        "/nix",
        "/bin",
        "/usr",
        "/etc",
        "/lib",
        "/lib64",
        "/run/current-system",
        "/run/systemd/resolve/stub-resolv.conf",

        "$XDG_CONFIG_HOME",
        "~/.bashrc",
        "~/.bash_profile",
        "~/.profile",

        "$GHQ_ROOT",
      ]
      tmpfs = [
        "/tmp",
        "$TMPDIR",

        "$XDG_CACHE_HOME",
        "$XDG_STATE_HOME",
        "$XDG_DATA_HOME",
      ]
    [[bash.bwrap.stages]]
      rw = [
        "$CARGO_HOME",
      ]
