# default config
# - copied to $XDG_CONFIG_HOME/vicode/config.toml if missing
# - defines defaults for missing top level values
# - sane defaults, except for fields marked with "CHANGE ME"

# TODO move comments from below to config.rs, except for "CHANGE ME" markers

shared = [] # if non-empty, user is expected to keep those readonly in the root ~forever; TODO make this make sense: change behaviour and/or explain better; maybe just wipe it from upperdir after modifying in the root
context_files = ["AGENTS.md"] # files to load into context from the commit, relative to workdir root; TODO make it possible to read from shared (i.e. if it's gitignored), or from repo root
primary_assistant = ["cerebras"] # CHANGE ME: list of assistants for new tabs to round robin over
subagent_assistant = [] # same as primary_assistant, if empty -- inherits from the parent agent

[keymap.cmdline]
"enter" = "input_submit"
"esc" = "input_exit"

[keymap.normal]
":" = "cmdline_enter"

"t" = "toggle_tools"
"r" = "toggle_reasoning"
"s" = "toggle_developer"

"j" = "tab_next"
"k" = "tab_prev"
"S-d" = "tab_delete"
"S-y" = "tab_duplicate"
"o" = "tab_new"

"S-q" = "quit"

"S-r" = "turn_retry"
"S-x" = "turn_abort"

"i" = "insert_enter"

"tab" = "assistant_next"

"up" = "scroll_line_up"
"down" = "scroll_line_down"
"C-y" = "scroll_line_up"
"C-e" = "scroll_line_down"
"C-u" = "scroll_half_page_up"
"C-d" = "scroll_half_page_down"
"C-b" = "scroll_page_up"
"C-f" = "scroll_page_down"
"[" = "scroll_prev_element"
"]" = "scroll_next_element"
"g" = "scroll_top"
"S-g" = "scroll_bottom"

"1" = "set_multiplier 1"
"2" = "set_multiplier 2"
"3" = "set_multiplier 3"
"4" = "set_multiplier 4"
"5" = "set_multiplier 5"
"6" = "set_multiplier 6"
"7" = "set_multiplier 7"
"8" = "set_multiplier 8"
"9" = "set_multiplier 9"

[keymap.insert]
"enter" = "input_submit"
"esc" = "input_exit"

[assistants.cerebras]
provider = "cerebras"
model = "zai-glm-4.7" # CHANGE ME
[assistants.gpt]
provider = "openai"
model = "gpt-5.1-codex-mini" # CHANGE ME
effort = "low" # CHANGE ME
[assistants.llama]
provider = "llama"
model = "dummy"
[assistants.zai]
provider = "zai"
model = "glm-5" # CHANGE ME

[providers.openrouter]
base_url = "https://openrouter.ai/api/v1"
key_command = "cat /run/agenix/openrouter" # CHANGE ME
[providers.llama]
base_url = "$LLAMA_HOST/v1" # CHANGE ME
developer_as_user = true
[providers.openai]
base_url = "https://api.openai.com/v1"
key_command = "cat /run/agenix/openai" # CHANGE ME
[providers.cerebras]
base_url = "https://api.cerebras.ai/v1"
key_command = "cat /run/agenix/cerebras" # CHANGE ME
api = "chat_completions"
reasoning_content_field = "reasoning"
reasoning_as_output = "think"
[providers.zai]
base_url = "https://api.z.ai/api/coding/paas/v4"
key_command = "cat /run/agenix/zai" # CHANGE ME
api = "chat_completions"
reasoning_content_field = "reasoning_content"

[bash]
  cmd = [
    "bash",
    "-c",
  ]
  [bash.bwrap]
    bin = "bwrap"
    args = [
      "--die-with-parent",
      "--proc",
      "/proc",
      "--dev",
      "/dev",
    ]
    # TODO make stages easier to redefine -- two enum variants: one appends, another replaces
    [[bash.bwrap.stages]]
      ro = [
        "/nix",
        "/bin",
        "/usr",
        "/etc",
        "/lib",
        "/lib64",
        "/run/current-system",
        "/run/systemd/resolve/stub-resolv.conf",

        "$XDG_CONFIG_HOME",
        "~/.bashrc",
        "~/.bash_profile",
        "~/.profile",
      ]
      tmpfs = [
        "/tmp",
        "$TMPDIR",

        "$XDG_CACHE_HOME",
        "$XDG_STATE_HOME",
        "$XDG_DATA_HOME",
      ]
