shared = ["target"]
context_files = ["AGENTS.md"]
primary_assistant = ["cerebras"]

[assistants.cerebras]
provider = "cerebras"
model = "zai-glm-4.7"
[assistants.gpt]
provider = "openai"
model = "gpt-5.1-codex-mini"
effort = "low"
[assistants.llama]
provider = "llama"
model = "dummy"
[assistants.zai]
provider = "zai"
model = "glm-5"

[providers.openrouter]
base_url = "https://openrouter.ai/api/v1"
key_command = "cat /run/agenix/openrouter"
[providers.llama]
base_url = "$LLAMA_HOST/v1"
developer_as_user = true
[providers.openai]
base_url = "https://api.openai.com/v1"
key_command = "cat /run/agenix/openai"
[providers.cerebras]
base_url = "https://api.cerebras.ai/v1"
key_command = "cat /run/agenix/cerebras"
api = "chat_completions"
reasoning_content_field = "reasoning"
reasoning_as_output = "think"
[providers.zai]
base_url = "https://api.z.ai/api/coding/paas/v4"
key_command = "cat /run/agenix/zai"
api = "chat_completions"
reasoning_content_field = "reasoning_content"

[bash]
  cmd = [
    "bash",
    "-c",
  ]
  [bash.bwrap]
    bin = "bwrap"
    args = [
      "--die-with-parent",
      "--proc",
      "/proc",
      "--dev",
      "/dev",
    ]
    [[bash.bwrap.stages]]
      ro = [
        "/nix",
        "/bin",
        "/usr",
        "/etc",
        "/lib",
        "/lib64",
        "/run/current-system",
        "/run/systemd/resolve/stub-resolv.conf",

        "$XDG_CONFIG_HOME",
        "~/.bashrc",
        "~/.bash_profile",
        "~/.profile",

        "$GHQ_ROOT",
      ]
      tmpfs = [
        "/tmp",
        "$TMPDIR",

        "$XDG_CACHE_HOME",
        "$XDG_STATE_HOME",
        "$XDG_DATA_HOME",
      ]
    [[bash.bwrap.stages]]
      rw = [
        "$CARGO_HOME",
      ]
