[insert]
"enter" = "input_submit"
"esc" = "input_exit"
"c-c" = "input_exit"
"c-n" = "completion_next"
"c-p" = "completion_prev"
"c-e" = "completion_cancel"

[cmdline]
"enter" = "input_submit"
"esc" = "input_exit"
"c-c" = "input_exit"
"c-n" = "completion_next"
"c-p" = "completion_prev"
"c-e" = "completion_cancel"

[normal]
"esc" = "toggle_tabs"
":" = "cmdline_enter"
"i" = "insert_enter"

"|" = "toggle_info"
"r" = "refresh_info"

"o" = "tab_new"
"s-d" = "tab_archive"
"s-y" = "tab_duplicate"

"s-r" = "turn_retry"
"s-s" = "turn_abort"

"s-u" = "msg_undo_user"
"tab" = "assistant_next"
"s-tab" = "assistant_prev"

"j" = "scroll down"
"k" = "scroll up"

"up" = "scroll line_up"
"down" = "scroll line_down"
"c-y" = "scroll line_up"
"c-e" = "scroll line_down"

"c-u" = "scroll half_page_up"
"c-d" = "scroll half_page_down"
"c-b" = "scroll page_up"
"c-f" = "scroll page_down"

"[" = "scroll prev_element"
"]" = "scroll next_element"

"g" = "scroll top"
"s-g" = "scroll bottom"
